import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
           
      <body style={{backgroundColor:'beige'}} className={inter.className}>
      <div style={{backgroundColor:'violet',color:'white'}} className='text-center p-5 mb-10'>Header</div>
      {children}
      <div style={{backgroundColor:'violet',color:'white'}} className='text-center p-5 fixed bottom-0 w-full'>Footer</div>
 </body>
    </html>
  )
}
